### ISSUE TITLE
Navigation bar is covering part of page contents

### ISSUE THREAD

**Issue by ArtPoon** [western-bioinfo/western-bioinfo.github.io#12]
![image](https://github.com/western-bioinfo/western-bioinfo.github.io/assets/1109328/948e8b0f-02f2-438d-adc7-72228b8de26b)

**Comment by mtran-code** [comment]
Seems to be a common issue with bootstrap theme. Fix is just to add/increase padding above body container.

In `assets/themes/lab/css/style.scss:21` it seems there's already padding to account for navbar overlap. We need to up this value from `50px` to `100px`, and that seems to do the trick. From what I can tell this only needs to be bumped for `padding-top`, and `padding-bottom` can be kept the same.

**Comment by ArtPoon** [comment]
Beauty 👍🏼
